Финальный проект спринта 11
CMEL123/java-filmorate pull request #2
Opened 2024-11-24 11:07 UTC by CMEL123

2024-11-25 11:27 UTC, vlolad requested changes
Привет!

Хорошая работа, новые фичи написаны корректно. Осталось поправить по коду пару моментов
1. Контроллеры взаимодействуют только с сервисами, без вызова хранилищ. Их надо полностью убрать из контроллеров
2. Есть пара моментов по методам самих хранилищ и доступу к данным
3. Валидация через аннотации после дублируется методами в хранилищах

В остальном все хорошо, молодец с:

Хорошего дня!

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
Контроллеры должны обращаться только к сервисам, не напрямую к хранилищу. Иначе нет смысла в подобной архитектуре: контроллер получает и оформляет запрос, после посылает его в нужный сервис, который уже сам по потребностям получает требуемое хранилище (попутно проводя валидацию, проверки доступа и т.д.)

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserService userService;
Тут аналогично, только обращение к сервису

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Long> friendIds = new HashSet<>(); //друзья
Правильно, что сразу использовал Set!

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void addUserIds(long userId) {
Лучше тогда переименовать методы - addLike и removeLike. А то неочевидно, что именно мы добавляем и убираем

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (listSortLikeFilms.size() > count) {
В стримах есть метод .limit(n), можно сразу при получении ограничить количество фильмов

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Должны инжектиться интерфейсы, не реализации

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        HashMap<Long, Film> filmsHash = inMemoryFilmStorage.getFilmsHash();
Получение мапы не требуется, можно просто получить все фильмы

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrHandler.java
> +    public class ErrorResponse {
Лучше вынести в отдельный класс

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/GeneratorId.java
> +package ru.yandex.practicum.filmorate.service;
Так как используется теперь в хранилищах, лучше перенести к ним в пакет

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Тоже поменять на интерфейс надо

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Getter
Геттер не нужен, доступ к полям хранилища не предусмотрен. Взаимодействие только через определенные методы и получение только требуемых объектов

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    @Getter
Геттер не нужен тоже

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (newUser.getName().isEmpty()) {
Это кстати лучше на сервисный слой перенести, т.к. относится к бизнес-логике
Плюс при работе с базой данных это будет проще, чем писать скрипт напрямую в базе

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private User checkNewUser(User user) {
Это всё уже валидируется аннотациями, можно убрать

2024-11-25 11:27 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void checkNewFilm(Film film) {
Уже добавлены же аннотации для валидации, тут не должно быть проблем с ней. Надо убрать

2024-11-26 10:50 UTC, CMEL123 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void checkNewFilm(Film film) {
Это я оставил для тестов.

2024-11-26 10:50 UTC, CMEL123 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private User checkNewUser(User user) {
Это я оставил для тестов.

2024-11-26 10:53 UTC, CMEL123 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    @Getter
Почему я использую его в методе getFriends

2024-11-27 13:54 UTC, vlolad requested changes
Привет!

Остались последние замечания по доступу к данным в хранилище, и можно приниматься)

По тестированию валидации оставил пример с тем, как её можно реализовать без методов на валидацию. Это не обязательно, но рекомендую сохранить - потом потребуется

Хорошего вечера!

2024-11-27 13:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private User checkNewUser(User user) {
Ладно, т.к. это пока доп. задание можно оставить. К теме про БД про это отдельное требование будет, там доработаем)

Но правильнее было бы переписать тесты с тестированием валидатора, например как тут описано: https://stackoverflow.com/questions/29069956/how-to-test-validation-annotations-of-a-class-using-junit

2024-11-27 13:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    @Getter
Да, и это ,как и в InMemoryFilmStorage, неправильная реализация
хэш-мапа сейчас в обоих хранилищах - это по сути все данные приложения. Сервисы прямого доступа к ним иметь не должны, вообще-вообще никак. За операции с хэш-мапой отвечает только само хранилище. Сервисы получают доступ к данным только через методы хранилища, но не к самому хранилищу

Т.е. если в getFriends тебе нужно получить всех пользователей, то надо использовать getUsers()
Комменты не писал специально по этому моменту в сервисах, но да - все getUsersHash() надо убрать. По фильмам вижу уже, что убрал, так что там ок)

2024-11-27 13:54 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Getter
Аннотацию забыл убрать!!!

2024-11-28 07:04 UTC, vlolad requested changes
Привет!

Ещё один финальный комментарий про хэш-мапу, чтобы закрепить правильный алгоритм поиска)

Постарался расписать подробно, если будут вопросы - пиши в Пачку
Хорошего дня!

2024-11-28 07:04 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            usersHash.put(user.getId(), user);
Уточню прошлые комменты - использование хэш-мапы в любом виде здесь не требуется)
Это работает, но давай лучше поправим, т.к. реализация неоптимальная. Если в сервисе будет, например, 1000 пользователей, то получать каждый раз полный список всех пользователей будет затратно (в плане алгоритма текущего решения)

Что в целом надо сделать, чтобы получить друзей пользователя:
1. Получить пользователя из хранилища
2. Получить из пользователя список с id его друзей
3. Получить друзей пользователя из хранилища

Как это сделать - up to you. Пока проще всего - получать в сервисе пользователя, и потом по Set с id друзей итерироваться в стриме или просто цикле, собирая список с помощью userStorage.getUser(friendId)

2024-11-28 07:04 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            usersHash.put(user.getId(), user);
Тут аналогично комментарию выше. Хэш-мапу собирать повторно не надо, просто в финальном стриме вместо `.map(usersHash::get)` лучше сделать получение из хранилища: `.map(userId -> userStorage.getUser(userId))`

2024-11-28 10:11 UTC, vlolad approved these changes
Всё, принято с:

2024-11-29 14:31 UTC, merged